apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-apps
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/pauldeniyi1/argocd-test-me-ga.git
    path: application-sets
    targetRevision: main ####this will be the main branch as this is only needed for just one apply
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - ServerSideApply=true